---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi
      version: 4.9.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  dependsOn:
    - name: traefik
      namespace: networking

  values:
    image:
      repository: jacobalberty/unifi
      tag: v7.1.61
      pullPolicy: IfNotPresent

    persistence:
      data:
        enabled: true
        existingClaim: unifi-pvc
    env:
      timezone: "America/Halifax"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "lan"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "unifi.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - unifi.${SECRET_DOMAIN}
            secretName: tls.unifi

    service:
      main:
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "unifi.${SECRET_DOMAIN}"
        loadBalancerIP: "${SVC_UNIFI_ADDR}"
        externalTrafficPolicy: Local
    # udp:
    #   enabled: true
    #   type: LoadBalancer
    #   externalIPs:
    #     - ${LB_UNIFI}
    #   externalTrafficPolicy: Local
    #   ports:
    #     stun:
    #       enabled: true
    #       port: 3478
    #       protocol: UDP
    #     syslog:
    #       enabled: true
    #       port: 5514
    #       protocol: UDP
    #     discovery:
    #       enabled: true
    #       port: 10001
    #       protocol: UDP

    resources:
      requests:
        memory: 500Mi
        cpu: 15m
      limits:
        memory: 750Mi
