---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: mosquitto
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/k8s-at-home/eclipse-mosquitto
      tag: v2.0.14
    auth:
      enabled: true
    controller:
      labels:
        app.kubernetes.io/part-of: mosquitto
    env:
      TZ: "America/Halifax"
    service:
      main:
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "mqtt.${SECRET_DOMAIN}"
        loadBalancerIP: "${LB_MOSQUITTO}"
        externalTrafficPolicy: Local
    persistence:
      data:
        enabled: true
        existingClaim: mqtt-data
      configinc:
        enabled: true
        existingClaim: mqtt-config
    resources:
      requests:
        memory: 32Mi
      limits:
        memory: 64Mi
