# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-config
    namespace: home
stringData: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14ckyfyz2ee72sdmtczq62rjxug9j6w6k34pfz0raq5965fcvrsusyvmuqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWU5CN1NtcHVZRkZPbG82
            TVp0ZmlDNE8yZDRPSFpmUEFRRXIzTEJFTWdVCnNBN2VjNnFHRitpWG1YM05RcE5P
            MWVEUWFGZFZSN3pkQkZZd3YrcEg0YzgKLS0tIFpiZmZnMDVlVmFvYjM1Y0FIeTkx
            Qkc3SkZ5OEFWaWVOb1FSZ2hGdXgraUEK6lcW6/xlz6NLLVYrz7ZvUnyJQJYuZzRQ
            32lKZ4nN0ga/6JDB5cY/cOJmNh5lQ631G/89Ii5XVNxLS8ltDJ4NiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-24T01:02:43Z"
    mac: ENC[AES256_GCM,data:aV/jExybK/V+sa/Sjg1ssDVHBRBZ7zjSt5AGD5IyHuja+cv1qts2dxD9kxyLw0yxLAs4PQLJB6pcXIPnPCkDcj7c622W3Utf2bz9MTALl4retTxm3S8KKH3mv/KepiXEHj9Qprp7T+bGgPzYbYPf5OEHXNM1AtCuQPnokw58tmg=,iv:aeCp57MmtZpnse/gaD1NUuJqRL5cK4dzHwXsL8e9AjU=,tag:NaCIGSPVfBwUTffpIvLy3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
