# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-config
    namespace: home
stringData:
    mqtt.conf: null
    mosquitto_pwd: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14ckyfyz2ee72sdmtczq62rjxug9j6w6k34pfz0raq5965fcvrsusyvmuqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWU5CN1NtcHVZRkZPbG82
            TVp0ZmlDNE8yZDRPSFpmUEFRRXIzTEJFTWdVCnNBN2VjNnFHRitpWG1YM05RcE5P
            MWVEUWFGZFZSN3pkQkZZd3YrcEg0YzgKLS0tIFpiZmZnMDVlVmFvYjM1Y0FIeTkx
            Qkc3SkZ5OEFWaWVOb1FSZ2hGdXgraUEK6lcW6/xlz6NLLVYrz7ZvUnyJQJYuZzRQ
            32lKZ4nN0ga/6JDB5cY/cOJmNh5lQ631G/89Ii5XVNxLS8ltDJ4NiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-24T01:38:24Z"
    mac: ENC[AES256_GCM,data:l5JySRiBJrpXXUukgq5zNO2wyLBfoh/mcGqu6E7qxDrtScGhKozx76ZjiIi1LXQRRR8sgqqPhmx4l316zdAkbuRsoesZkykWHaf5oQcOKo8UIV5CZTEDanr4TUtefmj6/ytdO8Iic66Hoi2KdFxfrGAxDPGmwBJ7JPDi/rMVUyo=,iv:Q3Whec6B9wIqENyYYyWDTcpCPoSZXPnyRL0IQ4FK8I4=,tag:Lb4sNUkVN3XtsXremHrkxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
