# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto
    namespace: home
stringData: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14ckyfyz2ee72sdmtczq62rjxug9j6w6k34pfz0raq5965fcvrsusyvmuqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWU5CN1NtcHVZRkZPbG82
            TVp0ZmlDNE8yZDRPSFpmUEFRRXIzTEJFTWdVCnNBN2VjNnFHRitpWG1YM05RcE5P
            MWVEUWFGZFZSN3pkQkZZd3YrcEg0YzgKLS0tIFpiZmZnMDVlVmFvYjM1Y0FIeTkx
            Qkc3SkZ5OEFWaWVOb1FSZ2hGdXgraUEK6lcW6/xlz6NLLVYrz7ZvUnyJQJYuZzRQ
            32lKZ4nN0ga/6JDB5cY/cOJmNh5lQ631G/89Ii5XVNxLS8ltDJ4NiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-24T00:30:05Z"
    mac: ENC[AES256_GCM,data:PDlC7SgW79ghYYcB8FnzXgMNrb/Zo48+NeJ4U93W82rBQNduG3BPbf0xWfDEG+Yw0aI6c4FQhlOfyKgdHjdHZPTRLiVwsZrhF9aGfvK3yF4rAGbi5KUz27kxtKcYmqtjSGvyLsjgq8UtopvoskyZCWLju9zLKVe4lHG6rSiyp0M=,iv:klVdAhI0vBd1AE/6agBLodIW6UNugUPtrNDc1lQN2QI=,tag:8z7inosqJL/1DBLn6pqZSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
