kind: Secret
ansible_user: ENC[AES256_GCM,data:Ve6eJPDfVPXO,iv:EyrWlR4bGM1PII8Unvrn/2a6PrxB2dy0r45b0jTv1us=,tag:6ysndp2JvkztOsWHwvH+ew==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:CxxIG0cjyAU=,iv:lNwBFg/YlsEHj80KBSSkZFZl42pVBclUj0H/84KDh0I=,tag:HEjc5eDZFZDcPRyyCiBpKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14ckyfyz2ee72sdmtczq62rjxug9j6w6k34pfz0raq5965fcvrsusyvmuqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaU1zcFFxeFhLalQ2TkVu
            a3hqZWo2MG05SkpQUURIK1paN0Eyd3daQVNnClhvQVdOR2FUUVBwcEtMaVAxcklS
            eXcwSHBMdC9aYWlrazMrUzZvRFdjSFkKLS0tIHZhQWxoU00wUktlMU0xNUFHRXNO
            ZzR4TUFScW9BaW1EaUtNY1FZQVhCNDgK2AQSA0WhkgcKX5KSSGCALUFn4lBUSzau
            DhsS/ENostPVRl2e82dPVlfwraGrdiwKH5ocCWSE9oZ7i4vcl+VteQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-22T19:52:28Z"
    mac: ENC[AES256_GCM,data:zeDatJTRh2jl012vgvfV2qfl965xw8EWwI3vvwFaoZaVPxGt+kvGM86C0ImZH+Mw9B/FG2uR7FVfMeyvUaCUHHE0n2MWW8IpVI6cJvK6PSjAaQIMmv5iVHjA1J9mwu5Oy97Qc6j20gata2CqrYLe+q/B5syAIc41iptAVBNbGzs=,iv:Z6fsYiHDX6q9uOFel57/5i8p8hmfK06OHAU+rGWz3UA=,tag:xztJy7u79An0P3wMs4WpBg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
