kind: Secret
ansible_user: ENC[AES256_GCM,data:1I4P/9uU84FQ,iv:ebTxTRQEYXVEWO29OnwMlW3LkDrLH0f6CsH/cWyt6tU=,tag:+i+30LQUcERvisw4iaQX9A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Sk5p6DLV7aY=,iv:sGUyRgKJVeVqXn2kFi7zJ83JVNaPCRNFT20jJc3Cc18=,tag:sHjnEdswhHFyPcoMVrncyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14ckyfyz2ee72sdmtczq62rjxug9j6w6k34pfz0raq5965fcvrsusyvmuqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UGhMRGtaN201VTBwOHdR
            M0lybEVjeXpubGg5bDlpWHlZNXk3WTRoclJNClF2U0RJUjZOTUNQdjU4MjBNSGtC
            Z0pyeXl3TkcwbC85dElkcTFwYk1ueDgKLS0tIC9kVXM2R3ZYRFE5aHdpRWJ2cGNl
            YjhuWEloZmRGWjVsYUZSQWFkYUxRdUEK4Q8rdkgHF2eAtHDTWAyPrBl3iMObNI8c
            7iDYAfGpTmrFn+xKdhfl0BebtwwzyuhbZc/kIYfLk1O4RSj2i3Pvog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-22T20:06:47Z"
    mac: ENC[AES256_GCM,data:QU0Ue2LWCaob+khpMCcaxInyHdHrixAGPzLDaL7WsGSac/vYcDMo6ulbA9R4ooEHS3x8FnSU70zRMltL2wUEL7WdLUfBtaBG7t2pk1fxoLYECjbCV8/yb8OQkm99qwirneoognwLhPLXY2k0/IWQLveej8+o+fhAAOYPrHVAWgE=,iv:HHdAng1IKsFQ9D1tESOiL4aRLrci6tNP8hHzIjR9+Q4=,tag:Hk6xDOrVis1vbMdAJ30vaA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
