kind: Secret
ansible_user: ENC[AES256_GCM,data:SI5MsvBOrzk+,iv:gn5pp5xxMteqJcdBfr6fxRAbMsnwx4ownVl/ttCjPcc=,tag:XZbp3A61vFDJUu7XRRoXiA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:qStxG1aa/kI=,iv:+UXpKfG9F7KelfT/7KLbkL0aL7ntDEOHuJYk7m/ZUPc=,tag:GCskMRCpiYAAaSEG8iFz4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14ckyfyz2ee72sdmtczq62rjxug9j6w6k34pfz0raq5965fcvrsusyvmuqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSL2FpMjdGd2FsV0F3cEpH
            SFVuT0xkNjBtK2pUT05PczJwdjVuRDQzL3dnCnhSU0tpYi94dnZFcXMxQTU0RDJC
            WWVTVU1uNldKQjlId3paZHZyRFdKaUEKLS0tIGhpUDFyeEwxVjlmbTNIbnJTOEdC
            NTl0aWlWeE5iVVRtSFl6L29Bd21oQzgK/OQtiqFCyH40bUNjyJla+fD9E9TDYvBn
            dANTLTM/SjivLkpugKnf6msbXIc6C++1xX8j8jufDdyrnHjrroctEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-22T19:52:28Z"
    mac: ENC[AES256_GCM,data:6FliPmfZZbTNsPojqV10Bp8nQDCw/b1zI8Cnv4ox8XHpZT1iiq0v5BjTIgThiMCjP9f2uWVWFpsePdl+YWHXbNgGKIJAgqoVue6F4Vx63hQJfYy0Xz3/kYhDJwPsaPB47l+OBynOFE83ZqoSIRs8KQymfQARwjYURSXbKZ5y62g=,iv:BZC3HhC1ivj5D5s16GYHOUsA9KfCSTBB5ukQM6nac9M=,tag:n4CvErciIG2JpchmHPcdeg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
