---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.10.50-192.168.10.59
  METALLB_TRAEFIK_ADDR: 192.168.10.50
  SVC_MOSQUITTO_ADDR: 192.168.10.51
  SVC_UNIFI_ADDR: 192.168.10.52
  TIMEZONE: America/Halifax
