# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:McGuBh7FE8a4TYysP5zRAIACRLEXpzTSIr9q6EL70N2bwn6Ifw==,iv:yodrq2pmX3SyhtE8ZLn9ONaiFkv3kjpefCLKN9dhfEo=,tag:aio3I9Sn5k7DqMBU86NKyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14ckyfyz2ee72sdmtczq62rjxug9j6w6k34pfz0raq5965fcvrsusyvmuqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUWZocFdIQlhTNUZuaXE5
            RjFtTXhWRWZXZVFuQ3pKRENoSjFETnUwUW5rCm0xK21uQjhmUXhIRnUydGJ4S2o2
            YnQ3d3d3OWNKNHdWQTVMd0dFTGlDU0UKLS0tIDl5UU9FYzB2NFZEZVNtNHo0ZjhE
            aXZrQjRWZGtpVXVvYTV0d3hnaUZuOFEKiUPYNuwM94Nt4UPFvbNAOQxs/KiXYouo
            /AR0qkpEbap0CbEItkIPzUmrUJATWGr5IfsVfUm6K+31Asfkx6qN4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-22T20:06:47Z"
    mac: ENC[AES256_GCM,data:n/98j3sbE6MRT1ny5G8EAZ8f49ZKCzq9MmAEJCXPwTrkC8WSqk7c0cgHeUW/Jmg9id3k0/y8OVInhLyAlgo2cmQwwt2gmzljVfScGGbW6bbC4TEVPcyRbIC7pCxCscZd8VHb8+Fz+p51eMIYpy9OUsL3TXOyRw/39It3HD0arLA=,iv:1nwSBo43JFDbYPgndzYI1XJ593MRzu4dXzOa+FhVGk8=,tag:EdfL7K7YKdaza/0rIRmhsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
