# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:4zJXWmoH793nE7DK8n8Nl5nipd1rQ8b9x6zNHPBTUZNUZ6FIig==,iv:JPxJRpVlYLwD5WxrkMMltqmeVGSUiq73Q9v5sMXc2ms=,tag:gldj+Dwg6NMzF+OhTAtZ1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14ckyfyz2ee72sdmtczq62rjxug9j6w6k34pfz0raq5965fcvrsusyvmuqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUldxTWkwbCs4azVsRTc4
            eGRQd0pqcjJ6eC82STk3WDdPM1doM1JHNFJ3Cm1FU3RKMThKZGZKZXZTaGxudW1n
            aWZVRm1pQStFbVFYc2dZY3FUVXVHbDgKLS0tIHhUSkJ6a2duVEVIbENENzZUOWw2
            cndhRmJsaFBxRFFRWlc1dTNKQ1BXVmsK/7Xa32Mi/dyXK9eYFqGdTfQ78yWgLwTe
            VVAluk1bKnkt43juB5OWB0u6J8juqt5XrWJAjJDsbzFJf6Eg6Pg4Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-22T19:33:33Z"
    mac: ENC[AES256_GCM,data:na81g0LFcnvsmCYlBK88pJ4Xx1dH48945/eNnAIfSDZLHyPC5wB6rfmhh4z3foIipKJJtTACq7Pg8FXmOCUdterQ3l2ymXfsu5rdBg7rbzOog3XBRkYsadOEy9h5Pn8xa45YRvGmY1Quk9NwjEl3BfNcUmhqLzEbDCcgFLzz8k0=,iv:bVnmcBBhiBgby8XUgv6qB/ew1Q2Pv/fs/YMdbpEprTs=,tag:Kkwbl349p1QVxFRJ8tQQcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
