# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:ymK60YbNw7VVdMvjUGgFu/oTwKFdgtss+kSCmKzybdbekJuJgg==,iv:tHeJ66ZHUQpXzVPWzrlPadRVf9mtSRuGenuD1sdh1zY=,tag:rU5z6CCXCD3MZEA9qmd+IQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14ckyfyz2ee72sdmtczq62rjxug9j6w6k34pfz0raq5965fcvrsusyvmuqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpb21ubXBDb1g3R2l0OWFa
            UnFWRGFpUnlHckNhSzVSbXVVS2RvMTROU2l3CmFtTnpoY1VtL0VxdE9hY1pqMWE1
            VW9BQnU5UHBZRUswd1EzTUZXL2hTalUKLS0tIFFGWHVNelBkWW0rdXVrTHd5TXlQ
            b3lRUFR2QjB5ZUJTU0ljWml4VEZNR3cKnHaCd9B1w0UmtpeDXGSOFSGY8DQDJoAx
            pkWfdqU2mWh4Aiwlpw8oKs7ir8byRwgdQAz2FIyysfdWm61Of4OYIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-22T19:52:28Z"
    mac: ENC[AES256_GCM,data:rloUAiVWGu2m2dvx/g/kOJD9m1qZ0kvcqKb+moPbZluNw+2K/YvmGCTp88kdReR4XtJC6GPKC5Y+HjdnHjeqgX2PGbhE9zO7x8gaKY+uonJOYRBoMXDsqZIwqYVtxnmMOWCB45uHBuyKkhMaxy7adMprx8AhMOMJnd7/sItJs7c=,iv:OjJwXuUpNA1a9/WpbexvVpcaIkSNg/8L0F4GG/PfLSc=,tag:vjtTmhNMmChoVk41BKLEEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
