# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:IBkFGr6HXEYiNh8N5l523FQAy9Mbva4Pn6Ob/hnbqPferFBW0Q==,iv:u8c/7aPLugCqocJ+w6CsIci/SkNXK52ITrl1sEbydQk=,tag:LYP7k+3hUqpvkZRLBl52gA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14ckyfyz2ee72sdmtczq62rjxug9j6w6k34pfz0raq5965fcvrsusyvmuqt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDb3NQb25uZlplMnJlbi9k
            UVc4UkpzdFRudXJkeGRWeXBKbWtreG1nN2lrCllyTm41M1Q1c3MyK3gzTTNwRHVl
            K1E1dmptQVp5eXAxRlV5QU9zek9oc2cKLS0tIEVUa1hLVW1zZzd2WHdZNjVEUzdw
            NjNLN0pzeEc1enVxNHk0NC9obHZveVkKt66FY62z7I5qO9LIc0OnAAI0xwa3EIGD
            JdvyCIJYUaRjj1Y70vqxlRg9/SDePvw0+PWoc8nHK52ORIfl9PVNrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-22T19:17:47Z"
    mac: ENC[AES256_GCM,data:2ydeDkOQmUZNOmuHR7hFr9YQfWig+HUAxvfr6UDPLPPEtGDfK0ZGsdbk46H/IaEGbEoL58eeIzeeEBP4igcx3nMA+VW7xdk1RwquUzbMDOYFkIpyJNOAe5M8NuhIJzImOXguk+0qbdHXzBgXbn6x7hTfX2atFtzt8rNmCivkKc0=,iv:iwcoXUy687jNaZBCKOsodLB1g3K02AndqNKkFv9T8LU=,tag:S3i6RhPt5Jlr9W5BcY2lnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
